version: '3.5'

services:
  proxy:
    build: proxy/
    env_file:
      - ./.env
    environment:
      DNS_SERVER: 127.0.0.11
      FRONTEND: http://frontend:7080
      QUERY_DISPATCHER: http://query-dispatcher
      ROBOKACHE: http://robokache:8080
  frontend:
    build: frontend/
  robokache:
    image: ghcr.io/ncats-gamma/robokache:v4.1.5
    volumes:
      - ./robokache-data:/app/data
  query-dispatcher:
    build: query-dispatcher/
    env_file:
      - ./.env
    environment:
      ROBOKACHE: http://robokache:8080
