version: '3.5'

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    environment:
      BRAND: qgraph
    volumes:
      - ./frontend:/app
      # Mount this in an anonymous volume so that the locally available node_modules
      # doesn't conflict with the one in the container
      - /app/node_modules
    command: $FRONTEND_COMMAND
  query-dispatcher:
    volumes:
      - ./query-dispatcher:/app
      - /app/node_modules
    environment:
      # deployed locally, we need to look at external robokop ara url
      ROBOKOP_URL: http://robokop.renci.org:7092
    command: npm run dev
  proxy:
    environment:
      ROBOKOP_URL: http://robokop.renci.org:7092
