version: '3.5'

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
    environment:
      MESSENGER_HOST: http://messenger:4868

networks:
  default:
    external:
      name: robokop_default    
