version: '3.5'

services:
  proxy:
    build: proxy/
    ports:
      - "80:80"
    environment:
      ROBOKACHE_URL: http://robokache
      FRONTEND_URL: http://frontend
      QUERYDISPATCHER_URL: http://query-dispatcher
  frontend:
    build: frontend/
  robokache:
    image: ghcr.io/ncats-gamma/robokache:v4.1.4
    volumes:
      - ./robokache-data:/app/data
  query-dispatcher:
    build: query-dispatcher/
    environment:
      ROBOKACHE_URL: http://robokache
