version: '3.5'

services:
  proxy:
    build: proxy/
    ports:
      - "80:80"
  frontend:
    build: frontend/
  robokache:
    image: docker.pkg.github.com/ncats-gamma/robokache/build:v4.1.2
    volumes:
      - ./robokache-data:/app/data
