version: '3.5'

services:
  proxy:
    build: proxy/
    environment:
      DNS_SERVER: 127.0.0.11
      FRONTEND: http://frontend:7080
      QUERY_DISPATCHER: http://query-dispatcher
      ROBOKACHE: http://robokache:8080
      # https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files
      # default external service urls with option to override with .env file
      STRIDER: ${STRIDER:-https://strider.renci.org/1.2}
      ARAGORN: ${ARAGORN:-https://aragorn.renci.org/1.2}
      ROBOKOP: ${ROBOKOP:-https://robokop-ara.apps.renci.org}
      NODE_NORMALIZER: ${NODE_NORMALIZER:-https://nodenormalization-sri.renci.org/}
      NAME_RESOLVER: ${NAME_RESOLVER:-https://name-resolution-sri.renci.org/}
      BIOLINK: ${BIOLINK:-https://raw.githubusercontent.com/biolink/biolink-model/2.2.5/biolink-model.yaml}
  frontend:
    build: frontend/
  robokache:
    image: ghcr.io/ncats-gamma/robokache:v4.1.5
    volumes:
      - ./robokache-data:/app/data
  query-dispatcher:
    build: query-dispatcher/
    environment:
      ROBOKACHE: http://robokache:8080
      STRIDER: ${STRIDER:-https://strider.renci.org/1.2}
      ARAGORN: ${ARAGORN:-https://aragorn.renci.org/1.2}
      ROBOKOP: ${ROBOKOP:-https://robokop-ara.apps.renci.org}
