name: 'Pull Request Feedback'

on: pull_request

jobs:
  eslint:
    name: Frontend ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Cache docker layers for faster build
      - uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build
        run: docker build -t qgraph -f Dockerfile.dev .
        

      - name: Run ESLint and get output
        run: docker run --name qgraph qgraph npm run --silent lint

  test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Cache docker layers for faster build
      - uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build
        run: docker build -t qgraph -f Dockerfile.test .

      - name: Run tests
        run: docker run --name qgraph qgraph npm run --silent test:pr
