name: 'Pull Request Feedback'

on: pull_request

jobs:
  eslint:
    name: Frontend ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build
        run: (cd frontend/ && docker build -t frontend -f Dockerfile.dev .)

      - name: Run ESLint and get summary
        id: run_eslint
        run: |
          OUTPUT="$(docker run frontend npm run --silent lint)"
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo ::set-env ESLINT_SUMMARY=${OUTPUT}

      - name: Report ESLint information as comment on pull request
        uses: mshick/add-pr-comment@v1
        with:
          message: ${{ env.ESLINT_SUMMARY }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
