name: 'Push to Github Container Registry'

on:
    pull_request:
        types: closed
        branches:
            - main

jobs:
    push_frontend:
        name: Push frontend image to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Push Frontend
              uses: docker/build-push-action@v1
              with:
                  path: ./frontend
                  dockerfile: Dockerfile.prod
                  username: ${{ github.actor }}
                  password: ${{ secrets.CR_PAT }}
                  registry: ghcr.io
                  tags: service/frontend:latest
    push_proxy:
        name: Push proxy image to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Push Frontend
              uses: docker/build-push-action@v1
              with:
                  path: ./proxy
                  username: ${{ github.actor }}
                  password: ${{ secrets.CR_PAT }}
                  registry: ghcr.io
                  tags: service/proxy:latest
