name: 'Push to Github Container Registry'

on:
    release:
        types: [published]

jobs:
    push_frontend:
        name: Push frontend image to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Lowercase repo name
              run: |
                echo REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Push Frontend
              uses: docker/build-push-action@v2
              with:
                  push: true
                  context: .
                  file: ./frontend/Dockerfile.prod
                  tags: latest,${{ steps.get_version.outputs.VERSION }}

    push_query_dispatcher:
        name: Push query dispatcher image to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Lowercase repo name
              run: |
                echo REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Push Query Dispatcher
              uses: docker/build-push-action@v2
              with:
                  push: true
                  context: .
                  file: ./query-dispatcher/Dockerfile
                  tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/query-dispatcher:latest,${{ env.REGISTRY }}/${{ env.REPOSITORY }}/query-dispatcher:${{ steps.get_version.outputs.VERSION }}

    push_proxy:
        name: Push proxy image to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Lowercase repo name
              run: |
                echo REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Push Proxy
              uses: docker/build-push-action@v2
              with:
                  push: true
                  context: .
                  file: ./proxy/Dockerfile
                  tags: latest,${{ steps.get_version.outputs.VERSION }}
