name: 'Push to Github Container Registry'

on:
    release:
        types: [published]

jobs:
    publish_qgraph:
        name: Push qgraph to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Push qgraph
              uses: docker/build-push-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  path: .
                  dockerfile: ./Dockerfile.prod
                  repository: ncats-gamma/qgraph
                  tags: latest,${{ steps.get_version.outputs.VERSION }}
