name: 'Push to Github Container Registry'

on:
    release:
        types: [published]

jobs:
    push_frontend:
        name: Push frontend image to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Push Frontend
              uses: docker/build-push-action@v2
              with:
                  push: true
                  context: .
                  file: ./frontend/Dockerfile.prod
                  tags: |
                    ghcr.io/qgraph/frontend:latest
                    ghcr.io/qgraph/frontend:${{ steps.get_version.outputs.VERSION }}

    push_query_dispatcher:
        name: Push query dispatcher image to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Push Query Dispatcher
              uses: docker/build-push-action@v2
              with:
                  push: true
                  context: .
                  file: ./query-dispatcher/Dockerfile
                  tags: |
                    ghcr.io/qgraph/query-dispatcher:latest
                    ghcr.io/qgraph/query-dispatcher:${{ steps.get_version.outputs.VERSION }}

    push_proxy:
        name: Push proxy image to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Push Proxy
              uses: docker/build-push-action@v2
              with:
                  push: true
                  context: .
                  file: ./proxy/Dockerfile
                  tags: |
                    ghcr.io/qgraph/proxy:latest
                    ghcr.io/qgraph/proxy:${{ steps.get_version.outputs.VERSION }}
