name: 'Push to Github Container Registry'

on:
    release:
        types: [published]

jobs:
    push_frontend:
        name: Push frontend image to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Lowercase repo name
              run: |
                echo REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Push Frontend
              uses: docker/build-push-action@v1
              with:
                  path: ./frontend
                  dockerfile: frontend/Dockerfile.prod
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io
                  repository: ${{ env.REPOSITORY }}/frontend
                  tags: latest,${{ steps.get_version.outputs.VERSION }}

    push_query_dispatcher:
        name: Push query dispatcher image to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Lowercase repo name
              run: |
                echo REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Push QueryDispatcher
              uses: docker/build-push-action@v1
              with:
                  path: ./query-dispatcher
                  dockerfile: query-dispatcher/Dockerfile
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io
                  repository: ${{ env.REPOSITORY }}/query-dispatcher
                  tags: latest,${{ steps.get_version.outputs.VERSION }}

    push_proxy:
        name: Push proxy image to GitHub Container Registry.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Lowercase repo name
              run: |
                echo REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Push Frontend
              uses: docker/build-push-action@v1
              with:
                  path: ./proxy
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io
                  repository: ${{ env.REPOSITORY }}/proxy
                  tags: latest,${{ steps.get_version.outputs.VERSION }}
